# infrastructure/kubernetes/production/datalake-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: datalake-config
data:
  ENVIRONMENT: production
  S3_ENDPOINT: http://minio.datalake.svc.cluster.local:9000
  SPARK_MASTER: spark://spark-master.datalake.svc.cluster.local:7077
  TRINO_HOST: trino.datalake.svc.cluster.local
  AIRFLOW_DATABASE_HOST: postgres.datalake.svc.cluster.local
  PROMETHEUS_ENDPOINT: http://prometheus.monitoring.svc.cluster.local:9090
---
apiVersion: v1
kind: Secret
metadata:
  name: datalake-secrets
type: Opaque
stringData:
  MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
