# infrastructure/monitoring/prometheus-test.yml
global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
- "alert_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets: [ 'alertmanager:9093' ]

scrape_configs:
- job_name: 'datalake-test'
  static_configs:
  - targets:
    - 'spark-master:8080'
    - 'trino:8081'
    - 'airflow-webserver:8082'
  metrics_path: '/metrics'
