global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'datalake'
  static_configs:
  - targets:
    - 'spark-master:8080'
    - 'trino:8081'
    - 'airflow-webserver:8082'
    - 'postgres-exporter:9187'
