# infrastructure/monitoring/production/prometheus-prod.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
- /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
- job_name: 'datalake-production'
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [ __meta_kubernetes_pod_label_app ]
    regex: datalake
    action: keep
